<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "indieweb"
 *
 * Auto generated by Extension Builder 2014-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'IndieWeb Publishing Tools',
	'description' => 'Growing collection of IndieWeb publishing tools for TYPO3 sites, currently featuring Webmentions',
	'category' => 'plugin',
	'author' => 'Joschi Kuphal',
	'author_email' => 'joschi@kuphal.net',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);