# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2014
  project: IndieWeb Publishing Tools
  version: 0.1.0
  release: 0.1.0-beta
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - indieweb.tex
    - IndieWeb Publishing Tools
    - Joschi Kuphal
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme: typo3sphinx
  html_theme_path:
  - /usr/lib64/python2.7/site-packages/t3sphinx/themes
  - /usr/local/src/RestTools/ExtendingSphinxForTYPO3/src/t3sphinx/
...
